### Service Definition
kind: Service
apiVersion: v1
metadata:
  name: cluster-frequency-manager
  namespace: default
  labels:
    service: ClusterFrequencyManager

spec:
  type: NodePort
  selector:
    app: cluster-frequency-manager
    
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 50002
---
### Pod, exposed by service
apiVersion: v1
kind: Pod
metadata:
  name: cluster-frequency-manager
  namespace: default  
  labels:
    app: cluster-frequency-manager

spec:
  containers:
  - name: cluster-frequency-manager
    image: patrickkutch/clusterfrequencymanager
    imagePullPolicy: Always    
    #Must add the connection points to the NFD targets here:  Example:
    #args: ["-c", "0.0.0.0:5000", "-v","4","vcmts-master-1:50001",""vcmts-master-2:50001"]          

    args: ["-c", "0.0.0.0:5000", "-v","4"]          

    env:
    - name: PYTHONUNBUFFERED
      value: "0"        
      
    ports:
    - name: app-port 
      containerPort: 5000
     
 