kind: Service
apiVersion: v1
metadata:
  name: node-frequency-manager
  namespace: default
  labels:
    #locale: appremote
    service: NodeFrequencyManager

spec:
  type: NodePort
  selector:
    app: node-frequency-manager
    
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 50000 
---

apiVersion: v1
kind: Pod
metadata:
  name: node-frequency-manager
  namespace: default  
  labels:
    app: node-frequency-manager

spec:
  tolerations:
  - key: "cmk"
    operator: "Exists"

  containers:
  - name: node-frequency-manager
    image: patrickkutch/nodefrequencymanager
    imagePullPolicy: Always    
    args: ["-c", "0.0.0.0:5000"]          

    env:
    - name: PYTHONUNBUFFERED
      value: "0"        
    ports:
    - name: app-port 
      containerPort: 5000
      

